### ISSUE TITLE
json-api-client breaks serialization when working with associations

### ISSUE THREAD

**Issue by Fivell** [swisnl/json-api-client#36]
## Detailed description
Given I have Items
PostItem and CategoryItem 
PostItem has_one Category
I want to patch Post and unassign category relationship

```
$post = new PostItem();
$post->setId($postId);
$post->category()->associate(null);
$post->save(); // uses repository under the hood
```
I expect such payload to be generated by json-api-client
```
{"data":{"id":"1","type":"posts","relationships":{"category":{"data": null},"attributes":{}}} 
```

Actual behaviour
```
{"data":{"id":"1","type":"posts","relationships":{"category":{"data":{"type":"categories","id":null}}},"attributes":{"category_id": null}}}
```

so 1 issue here 
attributes are populated with category_id value , but post doesn't have it. 

also 1 notice

category relashionship data can have {"data": null } object instead of {"data":{"type":"categories","id":null}

possible bug is in this line https://github.com/swisnl/json-api-client/blame/7a0005837dc49c1723b8a1cd57a98653198bf531/src/Relations/HasOneRelation.php#L37

I do not know why such implementation exists but seems it is not by jsonapi spec

**Comment by bbrala** [comment]
Yeah this seems off-spec indeed. It should be `null` as [per spec](https://jsonapi.org/format/#crud-updating-to-one-relationships)

**Comment by Fivell** [comment]
@bbrala @JaZo  FYI we fixed first problem with this  https://github.com/didww/json-api-client/commit/e84bc708cf56aff37d1b68c8c9ad7e122e3d84d6

**Comment by bbrala** [comment]
Thanks for the headsup :)
