### ISSUE TITLE
post and patch are not working in master branch

### ISSUE THREAD

**Issue by Fivell** [swisnl/json-api-client#37]
## post and patch are not working in master branch

performing any post or patch request json-api-client fails with
```
TypeError: Argument 1 passed to Swis\JsonApi\Client\DocumentClient::sanitizeJson() must be of the type string, array given, called in .../vendor/swisnl/json-api-client/src/DocumentClient.php on line 103 
```

please check also my comment here https://github.com/swisnl/json-api-client/commit/571547804c1f8b226f312c6a7281783fbfc94938#r31782624

**Comment by JaZo** [comment]
@Fivell, thanks for reporting! Fixed in ec4a6f83c4da7daa57b8d5d937426e6e8030b538.
