### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by JaZo** [swisnl/json-api-client#46]
Taken from https://github.com/swisnl/json-api-client/issues/30#issuecomment-449949133

- [x] How to setup http client
> See https://github.com/swisnl/json-api-client#bind-clients.
- [x] How to work with relationships (for instance update post with several attributes and also change author within one request) https://jsonapi.org/format/#crud-updating-relationships
> See https://github.com/swisnl/json-api-client#itemhydrator.
- [x] How to setup nested includes (for instance City->Region->Country so fetch cities with include: "region.country") https://jsonapi.org/format/#fetching-includes
> See https://github.com/swisnl/json-api-client#request-parameters for fetching included items.
> See https://github.com/swisnl/json-api-client#itemhydrator for posting included items.
- [x] Recommended way and full example to test client classes mocking HTTP requests
> See https://github.com/swisnl/json-api-client#bind-clients and https://github.com/swisnl/php-http-fixture-client.
- [x] Support for singular resources without id e.g. GET /profile
> The `take` method can be used for this.
- [x] Top level meta vs resource level meta
> See https://github.com/swisnl/json-api-client#meta
- [x] How to paginate records
> See https://github.com/swisnl/json-api-client#request-parameters.
- [x] How to setup TypeMapper or Hydrator to work with current classes
> See https://github.com/swisnl/json-api-client#typemapper
- [x] How to handle different errors (400, 422 etc) https://jsonapi.org/format/#errors-processing
> See https://github.com/swisnl/json-api-client#handling-errors
- [x] Complex objects (how to create resource if one of the attributes or several are custom complex objects and have specific json serialization/deseralization logic)
> You can setup get/set mutators (see https://github.com/jenssegers/model#example) or use a class that implements `\JsonSerializable` (only for serialization).
- [x] Different naming support (camelcase/snakecase/dasherize, etc)
> See https://github.com/swisnl/json-api-client#naming-support
- [x] What is responsibility of each class in json-api-client library
> Most "public" classes are covered in the readme and the rest is self explanatory

**Comment by JaZo** [comment]
@Fivell, can you explain what you mean with "Support for singular resources"? Thanks!

**Comment by Fivell** [comment]
@JaZo  for now we use workaround with new additional method in repository
https://github.com/didww/didww-api-3-php-sdk/blob/master/src/Repository.php#L13

**Comment by JaZo** [comment]
@Fivell, thanks for the clarification! Because I removed the document type check earlier, you can now use the `all` method for this. Although the name does not suggest it returns singular resources, it should work just fine!

**Comment by Fivell** [comment]
@JaZo  I agree ```all```can be used but it seems like a naming issue, so while code reading developer need comment in all the time to make it understandable :)

**Comment by JaZo** [comment]
@Fivell, I've updated the readme or answered all questions in this issue. Please feel free to open a new issue if you have more questions.

**Comment by Fivell** [comment]
@JaZo  thanks, about meta is not clear, in docs it is covered only case when meta is in the top of document structure (https://jsonapi.org/format/#document-top-level), but  meta maybe also part of record itself and even part of relationship 
https://jsonapi.org/format/#document-resource-objects and https://jsonapi.org/format/#document-resource-object-relationships

**Comment by JaZo** [comment]
@Fivell, I've clarified the Links and Meta sections and added more examples.
