### ISSUE TITLE
How to set a relation to "null"?

### ISSUE THREAD

**Issue by V-Orbit** [swisnl/json-api-client#66]
Hi @JaZo ! Just don't figure how to set a relation to null when saving a content which had a previous relation set.
Relation "publisher" is a hasOne relation

This is the attributes/relations array prior to hydration. this array works as expected.

``` 
$ordineAttributes = [
                    note => $datiForm['note'],
                    'totale_ordine' => $datiForm['totale_ordine'],
                    'stato' => [
                        'id' => base64_decode($datiForm['stato'])
                    ],

/* THIS IS THE RELATION I WANT TO EVENTUALLY SET TO NULL (OR SOMEWHAT SIMILAR) */
                    'publisher' => [
                         'id' => $datiForm['publisher']
                    ],

                    'cliente' => [
                        'id' => $datiForm['cliente_id']
                    ],
                    'righe_ordine' => $ids,
                ];

$itemOrdineDocument = $itemHydrator->hydrate(
                        $typeMapper->getMapping('node--ordini'), 
                        $ordineAttributes,
                        $orderID
                ); 
```
I already tried to:

- [x] pass an empty `publisher` array
- [x] pass `publisher => null`
- [x] pass `"id" => "none" `
- [x] pass `"id" => "null" `
- [x] pass `"id" => null `
- [x] pass `"id" => 0 `

Of course, if I completely remove the `publisher` entry from the `ordineAttributes` array, the hydrator steps over and leaves the previous value unchanged.

What I'm doing wrong?

I also get errors when I do
``` 
$itemOrdineDocument->unsetRelation('publisher');
$ordineRepo->save($itemOrdineDocument);
```

**Comment by V-Orbit** [comment]
I also get errors when I do
``` 
$itemOrdineDocument->unsetRelation('publisher');
$ordineRepo->save($document);
```

**Comment by JaZo** [comment]
Good point! Currently you can't set a relation to null using the `ItemHydrator`, but you can do it manually:

```php
$item = $typeMapper->getMapping('node--ordini');
$item->publisher()->dissociate();
```

I'll leave this issue open to implement this in the `ItemHydrator`!

**Comment by V-Orbit** [comment]
@JaZo fantastic! So I was hitting the point. I implemented 

> 
> 
> Good point! Currently you can't set a relation to null using the `ItemHydrator`, but you can do it manually:
> 
> ```
> $item = $typeMapper->getMapping('node--ordini');
> $item->publisher()->dissociate();
> ```
> 
> I'll leave this issue open to implement this in the `ItemHydrator`!

@JaZo fantastic! So I hit the point. Figuring out the way to workaround that, I implemented the setter exactly as you stated, really little before you wrote the comment :-D

**Comment by JaZo** [comment]
@V-Orbit, [1.0.0](https://github.com/swisnl/json-api-client/releases/tag/1.0.0) is released 🎉 and this release includes this fix!

**Comment by V-Orbit** [comment]
Fantastic work @JaZo! I'll update the library immediately! thanks for your help 💓
