### ISSUE TITLE
LinksParser: Handle and debug error response when bad params are passed in filters / fields ecc.

### ISSUE THREAD

**Issue by V-Orbit** [swisnl/json-api-client#68]
When I pass a bad / not allowed param to the repo for retrieve, LinksParser always return a 

`Error links object MUST contain at least one of the following properties: about` 

statement, reporting no further information about the bad parameter which generated that error.
In my case, I passed a bad filter operator, `%3E%3D` instead of `>=` and I must halt LinksParser before line 53 to get what actually is in `$data` variable, as the Exception did not provide any useful further info to investigate to.

Dumping `$data` variable, it contains a stdClass object with only the `via` and `info` properties.
Pasting `via->href` link in postman, it finally shows the json:api response which had the `errors` object which finally explains verbose info about the error (in that case, a 400 with detailed explanation).

IMHO The `errors` response object from json:api should be included in the `about` property, in `$data` variable of LinkParser when throwing an Exception

**Comment by JaZo** [comment]
@V-Orbit, do you have code and JSON examples?

**Comment by V-Orbit** [comment]
I'm using contentacms.
this is the api response i get in case of error

{
    "jsonapi": {
        "version": "1.0",
        "meta": {
            "links": {
                "self": {
                    "href": "http://jsonapi.org/format/1.0/"
                }
            }
        }
    },
    "errors": [
        {
            "title": "Bad Request",
            "status": "400",
            "detail": "The '%3E%3D' operator is not allowed in a filter parameter.",
            "links": {
                "via": {
                    "href": "https://mydomain.it/api/node/ordini?filter%5BCliente%5D%5Bcondition%5D%5BmemberOf%5D=campi-group&filter%5BCliente%5D%5Bcondition%5D%5Boperator%5D=CONTAINS&filter%5BCliente%5D%5Bcondition%5D%5Bpath%5D=cliente.title&filter%5BCliente%5D%5Bcondition%5D%5Bvalue%5D=aaa&filter%5BData%20creazione%5D%5Bcondition%5D%5BmemberOf%5D=campi-group&filter%5BData%20creazione%5D%5Bcondition%5D%5Boperator%5D=CONTAINS&filter%5BData%20creazione%5D%5Bcondition%5D%5Bpath%5D=created&filter%5BData%20creazione%5D%5Bcondition%5D%5Bvalue%5D=aaa&filter%5BForm%5D%5Bcondition%5D%5BmemberOf%5D=campi-group&filter%5BForm%5D%5Bcondition%5D%5Boperator%5D=CONTAINS&filter%5BForm%5D%5Bcondition%5D%5Bpath%5D=form_di_origine.title&filter%5BForm%5D%5Bcondition%5D%5Bvalue%5D=aaa&filter%5BID%20Ordine%5D%5Bcondition%5D%5BmemberOf%5D=campi-group&filter%5BID%20Ordine%5D%5Bcondition%5D%5Boperator%5D=CONTAINS&filter%5BID%20Ordine%5D%5Bcondition%5D%5Bpath%5D=title&filter%5BID%20Ordine%5D%5Bcondition%5D%5Bvalue%5D=aaa&filter%5BStato%5D%5Bcondition%5D%5BmemberOf%5D=campi-group&filter%5BStato%5D%5Bcondition%5D%5Boperator%5D=CONTAINS&filter%5BStato%5D%5Bcondition%5D%5Bpath%5D=stato.name&filter%5BStato%5D%5Bcondition%5D%5Bvalue%5D=aaa&filter%5BTotale%20Ordine%5D%5Bcondition%5D%5BmemberOf%5D=campi-group&filter%5BTotale%20Ordine%5D%5Bcondition%5D%5Boperator%5D=CONTAINS&filter%5BTotale%20Ordine%5D%5Bcondition%5D%5Bpath%5D=totale_ordine&filter%5BTotale%20Ordine%5D%5Bcondition%5D%5Bvalue%5D=aaa&filter%5Bcampi-group%5D%5Bgroup%5D%5Bconjunction%5D=OR&filter%5Bdatefilter1%5D%5Bcondition%5D%5Boperator%5D=%253E%253D&filter%5Bdatefilter1%5D%5Bcondition%5D%5Bpath%5D=created&filter%5Bdatefilter1%5D%5Bcondition%5D%5Bvalue%5D=1577314800"
                },
                "info": {
                    "href": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1"
                }
            }
        }
    ]
}

**Comment by JaZo** [comment]
@V-Orbit, the exception is thrown because we expect an `about` member in the links object of the error. 
The [spec](https://jsonapi.org/format/#errors) [isn't unambiguous](https://discuss.jsonapi.org/t/errors-and-links/1227) about whether the error links object MUST contain an about member or not. We interpreted it as such, but I believe we should remove the restriction for now until it is clarified. I've opend #69 for this.

**Comment by JaZo** [comment]
N.B. I've opened an issue to clarify this in the spec: https://github.com/json-api/json-api/issues/1444

**Comment by JaZo** [comment]
A fix for this is released in [1.0.1](https://github.com/swisnl/json-api-client/releases/tag/1.0.1)!
