### ISSUE TITLE
Laravel 6.* support

### ISSUE THREAD

**Issue by ci83rtda** [swisnl/json-api-client#73]
Could you please make package compatible with Laravel 6.17.1

**Comment by JaZo** [comment]
Hi @ci83rtda, this client is compatible with Laravel 6.x (we use it ourselves with it). Do you get an error when trying to install? Can you please share some details so we can look into it?

**Comment by ci83rtda** [comment]
Hi @JaZo, sorry I was using an older version. I am closing this.
