### ISSUE TITLE
Getting back NULL data from Ghost CMS API even though the request is succeeding.

### ISSUE THREAD

**Issue by pdiveris** [swisnl/json-api-client#76]
I am trying to fetch data from Ghost CMS API. The document is coming back with no errors, but empty. That is, `$blogs = $document->getData()` returns NULL, even though a raw request returns a body. It seems to me that this is happening because the data is coming back in an array with key `'pages'` or `'blogs'` (not a `'data'=>[ ]` one )

## Detailed description

As above, I am firing a request, I get some data back - for instance the metadata with pagination information etc, but getData() yields NULL. I suspect that's because the Ghost API doesn't follow the "standard," in other words the data is not wrapped in a ['data'=>['...']] array.

The way I fire the request is as follows (I do pass some extra params in the Service Provider, e.g. AUTH):

```php

use App\Api\v1\Repositories\PostRepository;

$repository = app(PostRepository::class);

$document = $repository->all();

dump($blogs->getResponse());    // YIELDS NULL

  dump($document->getMeta());  // YIELDS actual pages number, limit, etc.
```

This is a *question*

Is there a way of accessing the raw data? Your MD file says so, but I can't get my head round it.

parse a 'raw' \Psr\Http\Message\ResponseInterface ?

## Context

I am trying to create "documents" and/or items by consuming the Ghost CMS API. 

How can it benefit other users?

It might be useful when data returned needs fiddling with before it can be consumed.

## Possible implementation

No suggestion

## Your environment

PHP 7.4
Laravel 7.6.2
Docker Ghost 3.2 instance
Working on mac with Docker..

The data returned from ghost looks like this:

```json
{
    "pages": [
        {
            "id": "5ebc205fabd4eb000100581c",
            "uuid": "b603a9a1-6938-4083-8a1b-a279ff846a29",
            "title": "Bespoke Solutions",
            "slug": "bespoke-solutions",
            "html": "<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. </p><p>Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure? </p><p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee.</p>",
            "comment_id": "5ebc205fabd4eb000100581c",
            "feature_image": null,
            "featured": false,
            "visibility": "public",
            "created_at": "2020-05-13T16:29:19.000+00:00",
            "updated_at": "2020-05-13T16:29:39.000+00:00",
            "published_at": "2020-05-13T16:29:39.000+00:00",
            "custom_excerpt": null,
            "codeinjection_head": null,
            "codeinjection_foot": null,
            "custom_template": null,
            "canonical_url": null,
            "url": "http://localhost:2368/bespoke-solutions/",
            "excerpt": "But I must explain to you how all this mistaken idea of denouncing pleasure and\npraising pain was born and I will give you a complete account of the system, and\nexpound the actual teachings of the great explorer of the truth, the\nmaster-builder of human happiness. No one rejects, dislikes, or avoids pleasure\nitself, because it is pleasure, but because those who do not know how to pursue\npleasure rationally encounter consequences that are extremely painful. \n\nNor again is there anyone who loves o",
            "reading_time": 1,
            "page": true,
            "og_image": null,
            "og_title": null,
            "og_description": null,
            "twitter_image": null,
            "twitter_title": null,
            "twitter_description": null,
            "meta_title": null,
            "meta_description": null
        }
  ]
}
```

**Comment by bbrala** [comment]
Hi,

This client is made for usage with servers that implement the json:api specification (https://jsonapi.org). The api you are trying to consume is not working with that specification. Unfortunately this means you cannot use this client.

**Comment by pdiveris** [comment]
My question is whethe I can intevene on the resulting data before the client tries to parse it.

**Comment by bbrala** [comment]
It relies on the structure of the specification to pasrse documents and does a lot of validation of documents adhere to the spec. So it is not really possible to change how the json should be formatted unfortunately.

**Comment by pdiveris** [comment]
OK, that's quite easy to do with custom DocumentParser and DocumentInterface. However, seeing as this question was quickly closed as a "no no," I will be forking this and adding the extra functionality, examples and docblocks as I work on it, with a view to helping others who would like to jsonapify an API that's almost there but not quite. 

Cheers.

**Comment by bbrala** [comment]
Fair enough, i didn't mean to insult you, really. That would probably work, but it kinda out of the designed scope of the package. Unless i misread intentions of the colleague who wrote it :) (ping @JaZo)

**Comment by JaZo** [comment]
This package is indeed specifically designed to work with servers following the JSON:API spec. Usage with non standard compliant or even other standards is out of the scope. However, it might be doable to write some custom logic and use it with other servers. But imho that misses its purpose as you would have to write substantial parts yourself and parsing the example you provided to a collection of models looks much easier.
