### ISSUE TITLE
Replace jenssegers/model dependency

### ISSUE THREAD

**Issue by JaZo** [swisnl/json-api-client#83]
## Detailed description

Replace [jenssegers/model](https://github.com/jenssegers/model) dependency.

## Context

jenssegers/model doesn't receive much love from its maintainer. Besides, it requires illuminate/support and efforts to remove this dependency are ignored; https://github.com/jenssegers/model/pull/37

## Possible implementation

Pull the class into this package and maintain it ourselves.

**Comment by bbrala** [comment]
As talked about the current PR removed the dependency, but before a 2.0 release we need to clean up the separation of `Model` and `Item`. Seems like `Model` should be removed.
