### ISSUE TITLE
Drop nyholm/psr7 dependency

### ISSUE THREAD

**Issue by JaZo** [swisnl/json-api-client#85]
## Detailed description

Drop nyholm/psr7 dependency.

## Context

When https://github.com/guzzle/psr7/issues/327 is closed and guzzle/psr7 has a new major we can drop this dependency and leave it to the consumer.

**Comment by bbrala** [comment]
Well, RC1 has been out for a while, but we are waiting for stable i guess?

**Comment by JaZo** [comment]
Guzzle added support for guzzle/prs7 v2 in [7.3.0](https://github.com/guzzle/guzzle/blob/7.3.0/CHANGELOG.md#730---2021-03-23), so if your minimum stability is set to RC you'll get v2. I think it's safe to drop nyholm/psr7.

**Comment by bbrala** [comment]
Yeah i agree :)

**Comment by JaZo** [comment]
https://github.com/guzzle/psr7/releases/tag/2.0.0 🎉
