### ISSUE TITLE
Feature request: Split the Repository into traits

### ISSUE THREAD

**Issue by tomasvanrijsse** [swisnl/json-api-client#91]
## Detailed description

Our repositories don't always include all the CRUD actions. 
e.g. we have read-only resources that only include the GET index and GET singular resource endpoints.
If I'd extend `Swis\JsonApi\Client\Repository` our repositories would have methods that call non-existing endpoints.
To prevent this I have created custom repositories that basically have a selection of the  `Swis\JsonApi\Client\Repository` methods.

## Possible implementation

The `Swis\JsonApi\Client\Repository` class consists of all the CRUD methods.
If these methods would be moved to traits and the Repository would use those, the class would work the same.
It would also enable custom repositories with just a few of these traits, without having to rewrite them.
We could then make repositories ourselves using your traits like `hasIndexAction` and `hasDeleteAction`.

**Comment by JaZo** [comment]
Sounds good, we're open to pull requests!
