### ISSUE TITLE
ParamNameMismatch

### ISSUE THREAD

**Issue by NorthenIrbis** [swisnl/json-api-client#96]
The class Item uses a trait src/Concerns/HasRelations.php and implements an interface src/Interfaces/ItemInterface.php.
the parameters` name in method setRelation of HasRelation don`t match with method setRelation of ItemInterface.

You might read in https://psalm.dev/docs/running_psalm/issues/ParamNameMismatch/ about it.

I suggest to rename parameters` name in method setRelation in classes which implements ItemInterface.

**Comment by JaZo** [comment]
Thanks, fixed in d20c349!

**Comment by NorthenIrbis** [comment]
Not at all!
Thank you too! )
